= AWS SQS to Solace Event Broker

== Overview

In this example, we'll consume messages from an AWS SQS Queue and send them to a Solace Event Broker via JMS protocol.

== Prerequisites

First start a Solace Event Broker via the following docker compose repository: https://github.com/SolaceLabs/solace-single-docker-compose

Clone the project and run 
----
docker-compose -f PubSubStandard_singleNode.yml up -d
----

Visit localhost:8080

and create a queue named jms-test in the UI.

== AWS SQS Queue

Create an AWS SQS Queue named solace queue in the AWS Console, select the correct region of your choice.

== Set Application Properties

In 'application.properties' file add the correct host to solace.jms.host property.

== Run the application

[source,shell]
----
$ mvn clean compile quarkus:dev
----

The above command compiles the project, starts the application and lets the Quarkus tooling watch for changes in your
workspace. Any modifications in your project will automatically take effect in the running application.

TIP: Please refer to the Development mode section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_development_mode[Camel Quarkus User guide] for more details.

After the application is started, you can send messages to the Solace Queue by sending Events to AWS SQS Queue

----
aws sqs send-message --queue-url <sqs_queue_url> --message-body "Test JMS"
----

In the application logs you will see:

----
2025-03-24 17:41:55,789 INFO  [MessageBridgeRoute:30] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Sending message to Solace: Test JMS
2025-03-24 17:41:55,797 INFO  [com.sol.tra.imp.net.NettyTransportExecutorService] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Epoll is enabled; Netty 4.1.118.Final
2025-03-24 17:41:55,800 INFO  [com.sol.jcs.pro.imp.TcpClientChannel] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Client-3: Connecting to host 'orig=tcp://172.18.0.2, scheme=tcp://, host=172.18.0.2' (host 1 of 1, smfclient 3, attempt 1 of 1, this_host_attempt: 1 of 1)
2025-03-24 17:41:55,807 INFO  [com.sol.jcs.imp.JCSMPBasicSession] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Client-3: AdCtrl version changes: 2->4
2025-03-24 17:41:55,809 INFO  [com.sol.jcs.pro.imp.TcpClientChannel] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Client-3: Connected to host 'orig=tcp://172.18.0.2, scheme=tcp://, host=172.18.0.2' (smfclient 3) local(/172.18.0.1:34416) remote(172.18.0.2/172.18.0.2:55555)
2025-03-24 17:41:55,940 INFO  [com.sol.jcs.pro.imp.TcpClientChannel] (Camel (camel-1) thread #1 - aws2-sqs://solace-queue) Client-3: Channel Closed (smfclient 3)
2025-03-24 17:41:55,948 INFO  [MessageBridgeRoute:35] (Camel (camel-1) thread #3 - JmsConsumer[jms-test]) Consuming message from Solace: Test JMS
----

The message is initially dispatched to an Solace queue, then relayed to an Consumed and Logged.


=== Package and run the application

Once you are done with developing you may want to package and run the application.

TIP: Find more details about the JVM mode and Native mode in the Package and run section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_package_and_run_the_application[Camel Quarkus User guide]

==== JVM mode

[source,shell]
----
$ mvn clean package
$ java -jar target/quarkus-app/quarkus-run.jar
...
[io.quarkus] (main) camel-quarkus-examples-... started in 1.163s.
----
